# Generated by Django 6.0.6 on 2026-07-05 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('current_season', models.PositiveIntegerField(default=1)),
                ('current_episode', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('WATCHING', 'Watching'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('DROPPED', 'Dropped'), ('PLAN_TO_WATCH', 'Plan to Watch')], default='WATCHING', max_length=50)),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['-updated_at'],
            },
        ),
    ]
